### ISSUE TITLE
Скриншоты в отчетах

### ISSUE THREAD

**Issue by pbezpal** [selenide-examples/selenide-allure-junit#2]
Доброго времени суток. Попробовал ваш атач для своих тестов, но у меня не прикрепляются скриншоты в отчете. Код своих тестов смогу приложить только в понедельник. Спасибо.

**Comment by pbezpal** [comment]
Нашел решение, использую библиотеку aShot

**Comment by asolntsev** [comment]
Не понимаю, какая связь? Ашот ведь умеет сравнивать скриншоты между собой, а не прикреплять их куда-либо.

**Comment by pbezpal** [comment]
Я понял почему у меня не получалось, по вашему примеру. Я в итоге сделал так
[screenshot](https://github.com/pbezpal/itphone/blob/master/src/main/java/HelperClasses/ScreenshotTests.java)
