### ISSUE TITLE
allure+selenide+testng

### ISSUE THREAD

**Issue by lorasham** [selenide-examples/selenide-allure-junit#25]
Hi there
I can't add a listener when I use testNG with selenide, what is the alternative for this line to add a listener:
 SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(false));

**Comment by asolntsev** [comment]
@lorasham Yes, this is the right line. 
What exactly means "I can't add a listener"? Sure you can :)

**Comment by asolntsev** [comment]
@lorasham What can I do? I don't see your code. 
Probably you added the dependency with a wrong scope, or you forgot to re-import Maven project in IDEA etc.
