### ISSUE TITLE
Clear cache after test ends to prevent same user login again

### ISSUE THREAD

**Issue by sridharaiyer** [selenide-examples/selenide-allure-junit#32]
Hi I have a test where different users login and different points in the same test. I also have 2 tests where the login user is different. What is happening is, when the driver quits after an assertion failure and tries to login again for the next test, it logs in with the previous user. What can be done to clear the cache after the driver quits?

OS: MacOs
Chrome Driver: 101.0.4951.41
Selenide: 6.4.0

**Comment by asolntsev** [comment]
There are two major approaches to this problem:
1. Reopen the browser before every test
  * Pros: guaranteed independent tests
  * Cons: Slow
2. Re-use the browser between tests, but clear the state before every test:
  * Clear cookies
  * Clear cache
  * Clear localStorage
  * Clear sessionStorage
  * etc.

I personally prefer the 2nd way. It's much faster. And Selenide provides methods to clear cookies, cookies and storage.
