### ISSUE TITLE
Screenshots between Allure steps

### ISSUE THREAD

**Issue by loordbarringtn** [selenide-examples/selenide-allure-junit#7]
Уважаемый Андрей! 
Хотел бы спросить насчет данного кода: 
```
>   @Attachment(type = "image/png")
>   public byte[] screenshot() throws IOException {
>     File screenshot = Screenshots.getLastScreenshot();
>     return screenshot == null ? null : Files.toByteArray(screenshot);
>   }
```

Есть задача сделать скриншоты между шагами Алюра. 
Если просто данный метод  screenshot(); расставить между шагами, то скриншотов реально в отчёте Allure нет:
<img width="623" alt="Screenshot 2020-05-23 at 00 03 37" src="https://user-images.githubusercontent.com/55858015/82709310-f77ef780-9c88-11ea-9fa4-1c1c2de5b4f9.png">

Пришлось делать так:
```
    public void makeScreenshot(String fileName) {
        try {
            Allure.addAttachment(fileName + ".png", new FileInputStream(screenshot(fileName+getCurrentDateAndTime())));
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }}

```

Как можно сделать максимально правильно, чтобы скриншоты появлялись между шагами Алюра? Почему Ваш метод скриншотов не добавляет? (был бы благодарен за объяснение)
Спасибо заранее!

**Comment by asolntsev** [comment]
@loordbarringtn Честно скажу, не знаю, почему метод не добавляет. Я сам аллюр почти не использую. 

Если вы спрашиваете, как правильно, то может быть, правильно не делать скриншоты между шагами? Если там что-то важное происходит, то пусть это будут отдельные шаги. Иначе в чём тогда смысл шагов вообще?
