### ISSUE TITLE
ChromeDriver is not started when running tests form command line

### ISSUE THREAD

**Issue by AlexChernookov** [selenide-examples/selenide-allure-junit#9]
Hi all, 
I've faced a problem when I run tests form this example form command line 'mvn clean test' no ChromeDrivers were run

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.selenide.examples.GoogleSearchTest
Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 39783
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
авг. 02, 2020 10:35:47 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

after this line, nothing is happened for 1 or 2 min and then 

[ERROR] Tests run: 6, Failures: 1, Errors: 2, Skipped: 2, Time elapsed: 37.161 s <<< FAILURE! - in org.selenide.examples.InternetBankTest
[ERROR] userCanLoginToBspbDemo(org.selenide.examples.InternetBankTest)  Time elapsed: 16.083 s  <<< FAILURE!
com.codeborne.selenide.ex.ElementNotFound: 

When I'm running tests for IDE it's working fine. 

Could you please tell me what is wrong? 

BR
Oleksandr

**Comment by asolntsev** [comment]
@AlexChernookov Why do you think that "no ChromeDrivers were run"? I see in logs:
> ChromeDriver was started successfully.

Yes, `InternetBankTest` is flaky because domain https://idemo.bspb.ru is sometimes resolved very slowly. I don't know the reason. :( Probably we should just ignore `InternetBankTest`.

**Comment by AlexChernookov** [comment]
@asolntsev Thanks a lot for your answer. I've found the reason, chromedriver was started but in headless mode. Didn't look carefully in pom.xml. Maybe it would be better to set **selenide.headless** property to false?

**Comment by asolntsev** [comment]
@AlexChernookov I added `selenide.headless=true` because it makes it easier to run those tests on CI. 
But well, now I remove this flag by default. Now it's added only when running tests on TravisCI.
